language: android
jdk: oraclejdk8
dist: trusty

env:
  global:

android:
  components:
   - tools
   - platform-tools
   - build-tools-30.0.3
   - android-30

before_install:
- chmod +x gradlew
script:
 - ./gradlew build connectedCheck 

before_script: